---
# ============================================================
# DO NOT commit this file with real values to Git.
# Use: kubectl apply -f secret.yaml

# For production use vault for secrets
# ============================================================
apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-secret
  namespace: nextcloud
type: Opaque
stringData:
  # PostgreSQL
  POSTGRES_DB: "nextcloud"
  POSTGRES_USER: "nextcloud"
  POSTGRES_PASSWORD: "StrongPostgresPassword123"      # Change this

  # Redis
  REDIS_PASSWORD: "StrongRedisPassword123"            # Change this

  # Nextcloud Admin
  NEXTCLOUD_ADMIN_USER: "admin"
  NEXTCLOUD_ADMIN_PASSWORD: "StrongAdminPassword123"  # Change this