# longhorn values
defaultSettings:
  defaultDataPath: /var/lib/longhorn
  defaultReplicaCount: 3
  storageMinimalAvailablePercentage: 15
  nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod

persistence:
  defaultClass: true
  defaultClassReplicaCount: 3
  reclaimPolicy: Retain